error handling

diff --git a/rix-run b/rix-run
--- a/rix-run
+++ b/rix-run
@@ -16,7 +16,13 @@ then
 fi
 
 
-echo "Generating default.nix configuration..."
+if test -f "${1}"; then
+  echo "Generating default.nix configuration..."    
+else
+  echo "Error: No R script provided. Use: rix-run <your-script>.R"
+  exit 2
+fi
+
 NIX_TMP_DIR=$(mktemp -d /tmp/rix.XXXXXXXXX)
 RIX_R_SCRIPT_PATH="$(mktemp /tmp/rix.XXXXXXXXX.R)"
 cat <<EOF > "$RIX_R_SCRIPT_PATH"
@@ -82,14 +88,13 @@ nix-shell --expr "$(curl -sl https://raw.githubusercontent.com/jrosell/rix-run/m
 # nix-shell --expr "$(cat inst/extdata/rix.nix)" --run "Rscript --no-site-file --no-environ --no-restore $RIX_R_SCRIPT_PATH ${1}" > $NIX_TMP
 NIX_FILE=`cat $NIX_TMP | grep '^/tmp/' | grep 'default.nix'`
 # cat $NIX_TMP
-rm $NIX_TMP
 rm $RIX_R_SCRIPT_PATH
 
-
-if [[ $(wc -l < $NIX_FILE) -ge 2 ]]; then    
+if [[ $(wc -l < "$NIX_FILE") -ge 2 ]]; then    
   echo "Runing nix-shell $NIX_FILE ${1}..."
+  rm $NIX_TMP
 else
-  echo "Error when generating the configuration file."
+  echo "Error when generating the configuration file. Check for errors on the $NIX_TMP file."
   exit 2
 fi
 nix-shell --expr "$(cat $NIX_FILE)" --run "Rscript  \
